from . import tour
from . import participant
from . import sale_order_line_inherit
from . import flight
from . import sale_order_inherit
from . import product_template_extension
from . import hr_employee_extend
from . import hr_contract_extend
from . import external_reservation
from . import product_package
from . import tour_type
from . import ticket_daily_counter
from . import res_partner_extend