{
    "name": "Tour Minimal Odoo 17",
    "version": "1.0",
    "summary": "Módulo mínimo para Odoo 17",
    "author": "ChatGPT",
    "depends": ["base","product",'hr_contract',"hr","fleet","sale","hr_expense","bi_hr_payroll"],
    'data': [
        #'security/groups.xml',
        'security/ir.model.access.csv',
        #'security/security.xml',
        'views/tour_minimal_views.xml',
        'views/tour_minimal_modifiers.xml',
        'views/product_template_view.xml',
        'views/tour_participant_views.xml',
        'views/sale_order_inherit_views.xml',
        #'views/wizard/tour_selection_wizard_views.xml',
        #'views/wizard/tour_selection_external_wizard_views.xml',
        'views/external_activity_views.xml',
        'views/hr_employee_views.xml',
        'views/product_template_package_views.xml',
        'views/hr_contract_currency_readonly.xml',
        'data/tour_type_data.xml',
        'views/tour_private_calendar_views.xml',
        'views/ticket_daily_counter_views.xml',
        'report/sale_order_report_inherit.xml',
        'report/report_header_inherit.xml',
        'data/product_tour_leader_discount.xml',
        'views/participant_move_wizard.xml',
    ],
    'assets': {
        'web.report_assets_common': [
            'tour_minimal_odoo17/static/src/css/report_header.css',
        ],
    },
    "images": ['static/description/icon.png'],
    "installable": True,
    "application": True,
    "license": "LGPL-3"
}